language: php

env:
  global:
    - APPLICATION_ENV=devtest
    - APPLICATION_STORE=DE
    - PROJECT=demoshop
    - MODULE_DIR=module
    - SHOP_DIR=current
    - MODULE_NAME=fact-finder-sdk

#Possible travis events (push, pull_request, cron, or api)
matrix:
  fast_finish: true
  include:
     - php: "7.1"
       env:
          - TEST_GROUP=without-acceptance
          - ON_EVENTS=cron,push
          - PHPSTAN=1
     - php: "7.2"
       env:
          - TEST_GROUP=without-acceptance
          - ON_EVENTS=cron,push
          - DB=mysql
     - php: "7.1"
       env:
          - TEST_GROUP=acceptance
          - ON_EVENTS=push,cron
     - php: "7.2"
       env:
          - TEST_GROUP=acceptance
          - ON_EVENTS=push,cron
          - DB=mysql

addons:
  postgresql: 9.6
  mysql: 5.7

  apt:
    packages:
      - graphviz

  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql
  - mysql
  - redis
  - rabbitmq

sudo: required

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ $ON_EVENTS != *$TRAVIS_EVENT_TYPE* ]]; then exit ; fi
  - if [[ $DB == 'mysql' ]]; then chmod +x ./config/Shared/ci/travis/mysql/* ; fi
  - if [[ $DB == 'mysql' ]]; then ./config/Shared/ci/travis/mysql/travis_mysql_5.7.sh ; fi

install:
  - chmod -R a+x config/Shared/ci/travis/
  - if [[ -d 'vendor/spryker/spryker' ]] ; then cd vendor/spryker/spryker && git clean -f -d && cd - ; fi
  - composer remove --dev spryker/git-hook
  - composer install --optimize-autoloader --no-interaction
  - config/Shared/ci/travis/install_elasticsearch.sh

before_script:
  - nvm install 6

  - mkdir -p shared/data/common/jenkins
  - mkdir -p shared/data/common/jenkins/jobs
  - mkdir -p data/DE/cache/Yves/twig -m 0777
  - mkdir -p data/DE/cache/Zed/twig -m 0777
  - mkdir -p data/DE/logs -m 0777
  - chmod -R 777 data/

  - if [[ -z $DB ]]; then cat config/Shared/ci/travis/postgresql_ci.config >> config/Shared/ci/travis/config_ci.php ; fi
  - if [[ $DB == 'mysql' ]]; then cat config/Shared/ci/travis/mysql_ci.config >> config/Shared/ci/travis/config_ci.php ; fi

  - cp config/Shared/ci/travis/config_ci.php config/Shared/config_local.php

  - if [[ $DB == 'mysql' ]]; then sudo cp config/Shared/ci/travis/mysql/my.cnf /etc/ ; fi
  - if [[ $DB == 'mysql' ]]; then sudo service mysql restart ; fi

  - if [[ $TEST_GROUP == 'acceptance' ]]; then config/Shared/ci/travis/acceptance_env.sh ; fi

  - if [[ $TEST_GROUP == 'acceptance' ]]; then vendor/bin/install DE -r testing ; fi
  - if [[ $TEST_GROUP == 'without-acceptance' ]]; then vendor/bin/install DE -r testing -x frontend ; fi

script:
  - git clone -b '0.1.0' --single-branch https://github.com/spryker-eco/eco-ci.git ecoci
  - ./ecoci/build/travis.sh

notifications:
  email: false
